name: rewarity
description: Loyalty Management System
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Routing
  go_router: ^14.2.0

  # DI
  get_it: ^7.7.0

  # HTTP
  dio: ^5.6.0

  # State
  flutter_riverpod: ^2.5.1

  # JSON / immutables
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # Logging
  logger: ^2.4.0

  # Analytics (optional placeholder)
  firebase_analytics: ^10.10.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.9.3
  very_good_analysis: ^6.0.0
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/illustrations/logo.png
    - assets/illustrations/gradient_card.png
    - assets/illustrations/earn.png
    - assets/illustrations/redeem.png
    - assets/illustrations/tiers.png
    - assets/illustrations/referral.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
