name: rewarity
description: Loyalty Management System
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.0
  get_it: ^7.7.0
  dio: ^5.6.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  logger: ^2.4.0
  firebase_analytics: ^10.10.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.9.3
  very_good_analysis: ^6.0.0
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/illustrations/logo.png
    - assets/illustrations/gradient_card.png
    - assets/illustrations/earn.png
    - assets/illustrations/redeem.png
    - assets/illustrations/tiers.png
    - assets/illustrations/referral.png